# Generated by Django 4.2 on 2023-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='AFFILIATION',
            new_name='affiliation',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='EMAILID',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Phoneno',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='SPECIALIZATION',
            new_name='specialization',
        ),
    ]
