# Generated by Django 4.2 on 2023-06-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_rename_affiliation_doctor_affiliation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='affiliation',
            new_name='AFFILIATION',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='email_id',
            new_name='EMAILID',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_no',
            new_name='Phoneno',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='SPECIALIZATION',
        ),
    ]
