# Generated by Django 4.2 on 2023-06-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_rename_affiliation_doctor_affiliation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='AFFILIATION',
            new_name='Affiliation',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='EMAILID',
            new_name='Emailid',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='NAME',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='SPECIALIZATION',
            new_name='Specialization',
        ),
    ]
