# Generated by Django 4.2 on 2023-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_admindata_user1data_user2data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='data',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user1data',
            old_name='data',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user2data',
            old_name='data',
            new_name='password',
        ),
        migrations.AddField(
            model_name='admindata',
            name='username',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='user1data',
            name='username',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='user2data',
            name='username',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
    ]
