# Generated by Django 4.2 on 2023-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_auto_20230613_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Sub_Specialization',
            field=models.CharField(max_length=100),
        ),
    ]
