# Generated by Django 4.2 on 2023-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_alter_doctor_sub_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=255)),
                ('Sub_Specialization', models.CharField(max_length=255)),
            ],
        ),
    ]
